### ISSUE TITLE
Error using h5 created with MATLAB

### ISSUE THREAD

**Issue by MartinK84** [spinicist/riesling#23]
I have been trying to use my own data for the reconstruction of 3D-UTE data based on the tutorial notebook. What I did so far in MATLAB was reshape my data structures to the format required by riesling and create a header info struct. However, when trying a simple RSS reco riesling fails directly after or during loading of the trajectory. 

```
./riesling recon --verbosity=3 --rss --sdc=pipe UTE.h5
Starting operation: recon
Read wisdom successfully
Opened file UTE.h5 for reading
Reading info
Reading trajectory
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

The header I think and hope is set correctly:

```
./riesling hdr UTE.h5
Header
Matrix: 96 96 96
Voxel-size: 2.08333 2.08333    1.25
Read points: 122 Gap: 0
Hi-res spokes: 8002 Lo-res spokes: 0 Lo-res scale: 1
Channels: 16 Volumes: 1 TR: 1
Origin: 0 0 0
Direction:
1 0 0
0 1 0
0 0 1
```

The relevant MATLAB output used for creating the h5 file:

```
>> size(kspace_UTE)
ans =
          16         122        8002

>> size(traj_UTE)
ans =
           3         122        8002

>> write_riesling('UTE.h5', single(kspace_UTE), single(traj_UTE), info_UTE);
```

at this point, I'm a bit out of ideas without going into the code and starting to add additional debug output, any hints or ideas what I could be missing?

**Comment by spinicist** [comment]
To date I've only seen `std::bad_alloc` thrown when riesling has run out of memory - either due to a very large reconstruction, or on a grid job with memory constraints. Given the dimensions of your problem this seems unlikely.

Is it possible for you to share the `UTE.h5` file so I can investigate?

**Comment by MartinK84** [comment]
I will send you a link to the data via Twitter in a minute (don't want to publicly share it). Memory should not be an issue as that computation server has 768GB of RAM.

**Comment by spinicist** [comment]
The issue was thankfully a simple one - in your `Info` struct you had put `spokes_low` instead of `spokes_lo`. It appears the HDF5 library will happily skip over missing/mis-spelled fields and leave junk values there. On my machine `spokes_lo` was consequently being filled with a very large number, if the same happened on your machine I suspect it could overflow even 768 GB!

I have now added code to check that all the header fields riesling expects are actually present, and report if any are not found. I also changed the name of the header field in your file and managed to run the reconstruction.

**Comment by MartinK84** [comment]
Awesome thanks, will soon give it another try.

Does it make sense to give the MATLAB wrapper some additional features? It could basically also check the header names and possibly data types to avoid any fallout in the C++ backend.

**Comment by spinicist** [comment]
I have added checking of the header fields to the MATLAB code.

Note that I renamed the MATLAB files for consistency - they now all start with `riesling_`.

**Comment by MartinK84** [comment]
Great, looking good - issue closed
